@startuml active-agreements-seq
skinparam Shadowing false
skinparam DefaultFontName Bitstream Vera Sans
skinparam DefaultMonospacedFontName Bitstream Vera Sans Mono
skinparam SequenceMessageAlign direction
skinparam MaxMessageSize 250
skinparam Style strictuml
skinparam Monochrome true
skinparam Dpi 300

hide footbox

participant "i3M SDK" as SDK #white

participant "SCM" as SCM

box "DLT" #white
  participant "Index/Factory" as I
  ' participant "AgreementA" as A
end box

SDK->>SCM++: POST /query { query: 'agreements', filter: Filter }
note left 
For more information on the
<i>Filter</i> type look into the 
class diagram.
end note

SCM->>I++: get agreements \n{ filter: Filter }
I-->>SCM--: { [ Partial<Agreements> ] }

SCM-->>SDK--: { [ Partial<Agreements> ] }

@enduml
