@startuml agreements-seq
skinparam Shadowing false
skinparam DefaultFontName Bitstream Vera Sans
skinparam DefaultMonospacedFontName Bitstream Vera Sans Mono
skinparam SequenceMessageAlign direction
skinparam MaxMessageSize 250
skinparam Style strictuml
skinparam Monochrome true
skinparam Dpi 300

hide footbox

participant "i3M SDK" as SDK #white

participant "SCM" as SCM

box "DLT" #white
  participant "Index/Factory" as I
  ' participant "AgreementA" as A
end box

SDK->>SCM++: POST /query { query: 'agreements', args: AgreementsQueryArgs }
note left 
For more information on the types in 
use type look into the class diagram.
end note

SCM->>I++: get agreements \n{ filter: Partial<Agreement> }
I-->>SCM--: { [ Agreement ] }

SCM-->>SDK--: { [ Partial<Agreement> ] }

@enduml
